export const refs = {
  todoList: document.querySelector('.todo-list'),
  btnAdd: document.querySelector('.todo-add__button'),
  inputAddItem: document.querySelector('.todo-add__input'),
  inputSearch: document.querySelector('.todo-filter__input.search'),
  inputSort: document.querySelector('.todo-filter__input.sort'),
  inputPageLimit: document.querySelector('.page-limit'),
  clock: document.querySelector('.clock'),
  loadingHome: document.querySelector('.loading'),
  loadMoreBtn: document.querySelector('.load-more'),
  pageUpBtn: document.querySelector('.page-up'),
  body: document.querySelector('body'),
  totalItems: document.querySelector('.total-page'),
  inputPageLimitDefault: document.querySelector('.page-default'),
  weather: document.querySelector('.weather'),
  loadingWeather: document.querySelector('.weather__loading'),
};
